[vpn_gateway]
vpn-server ansible_host=192.168.56.10 ansible_user=sysadmin

[private_servers]
private-server-1 ansible_host=10.10.10.20 ansible_user=sysadmin
# tambahkan private-server-2, private-server-3, dst di sini
# tanpa perlu mengubah playbook
